### ISSUE TITLE
all: add a way to create create groups in `tdp-lib` sense and propagate variable through inheritance

### ISSUE THREAD

**Issue by gboutry** [TOSIT-IO/tdp-collection#138]
We need to be able to create group and propagate variables to the children through inheritance.

Example:

Group: `hdfs_datanode_config` belongs to the following groups:
- all
- hadoop
- hdfs
- hdfs_datanode
- hdfs_datanode_config

Therefore, if we have the following configurations:

```yaml
# all.yml
value_from_all: toto

hdfs_site:
  group_name: all
```
```yaml
# hdfs_datanode.yml
hdfs_site:
  group_name: hdfs_datanode
  datanode_key: super
```
```yaml
# hdfs_datanode_config.yml
hdfs_site:
  group_name: hdfs_datanode_config
  specific_key: "{{ value_from_all }}"
```

On the specific play hdfs/datanode/config.yml, the variables present in the play should be:
```yaml
value_from_all: toto
hdfs_site:
  datanode_key: super
  group_name: hdfs_datanode_config
  specific_key: toto
```

If an intermediate group does not exist, it shouldn't matter. It's not a problem.
The examples shown previously are not true examples, Do no use the key `group_name` in the implementatoin, if possible.
