### ISSUE TITLE
[Hive & PostgreSQL] - Validate/Init schema : Error & Lang

### ISSUE THREAD

**Issue by ChristopheLRTE** [TOSIT-IO/tdp-collection#283]
Hello,

Thank you for your work which has been much appreciated within our company.

We used the TDP using the "[Quick Start](https://github.com/TOSIT-IO/tdp-getting-started#quick-start)" contained in the tdp-getting-started repo. README.md file and found an issue with this [task : tdp-collection/roles/hive/common/tasks/init_schema.yml](https://github.com/TOSIT-IO/tdp-collection/blob/master/roles/hive/common/tasks/init_schema.yml) while deploying.

Here is the error message encountered when executing the Validate Hive Metastore Schema task :
```
TASK [tosit.tdp.common : Validate Hive Metastore schema] ***************************************************************************************************************************************************************
fatal: [master-03]: FAILED! => changed=false 
  cmd: |-
    /opt/tdp/hive/bin/hive  --config /etc/hive/conf.ms  --service schemaTool  -dbType postgres  -validate
  delta: '0:00:03.501206'
  end: '2022-05-11 14:54:42.290458'
  failed_when_result: true
  msg: non-zero return code
  rc: 1
  start: '2022-05-11 14:54:38.789252'
  stderr: |-
    SLF4J: Class path contains multiple SLF4J bindings.
    SLF4J: Found binding in [jar:file:/opt/tdp/apache-hive-3.1.3-TDP-0.1.0-SNAPSHOT-bin/lib/log4j-slf4j-impl-2.10.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: Found binding in [jar:file:/opt/tdp/hadoop-3.1.1-TDP-0.1.0-SNAPSHOT/share/hadoop/common/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
    SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
    org.apache.hadoop.hive.metastore.HiveMetaException: Failed to get schema version, Cause:ERREUR: la relation « VERSION » n'existe pas
      Position : 32
    Use --verbose for detailed stacktrace.
    *** schemaTool failed ***
  stderr_lines: <omitted>
  stdout: |-
    Starting metastore validation
  
    Validating schema version
  stdout_lines: <omitted> 
```

As a workaround, we add those lines in the [all.yml](https://github.com/TOSIT-IO/tdp-getting-started/blob/master/inventory/group_vars/all.yml) files in order to force the "en_US" LANG parameter for PostgreSQL (_i.e. our environments are in French by default and the error management is based, among other things, on an English character string from stderr_) :
```
# PostgreSQL

# Global configuration options that will be set in postgresql.conf.
postgresql_global_config_options:
  - option: unix_socket_directories
    value: '{{ postgresql_unix_socket_directories | join(",") }}'
# Ensure PostgreSQL prints errors message in english for
# ansible_roles/collections/ansible_collections/tosit/tdp/roles/hive/common/tasks/init_schema.yml
# to work.
  - option: lc_messages
    value: 'en_US.UTF-8'
```

Do you think this is really an issue and if so, does our workaround seem correct to you ?

Thank you for your help,
Cheers
