### ISSUE TITLE
hardcoded namenode config dir in hdfs ranger config

### ISSUE THREAD

**Issue by gboutry** [TOSIT-IO/tdp-collection#434]
The namenode configuration directory is hardcoded in https://github.com/TOSIT-IO/tdp-collection/blob/3af2052f08d3461bec66a1105d968aa9724b785a/roles/hdfs/ranger/tasks/config.yml

```yaml
# We also need to fix the path of the ranger-policymgr-ssl.xml containing the trustore properties in ranger-hdfs-security.xml
- name: Fix the path of ranger-policymgr-ssl.xml in ranger-hdfs-security-changes.cfg
  lineinfile:
    path: "{{ ranger_hdfs_install_dir }}/install/conf.templates/enable/ranger-hdfs-security-changes.cfg"
    regexp: '^ranger.plugin.hdfs.policy.rest.ssl.config.file\s+([^ ]+) (.*)$'
    line: 'ranger.plugin.hdfs.policy.rest.ssl.config.file    /etc/hadoop/conf.nn/ranger-policymgr-ssl.xml \2'
    backrefs: yes
```
