### ISSUE TITLE
ranger admin install.properties template rendered twice

### ISSUE THREAD

**Issue by jusstol** [TOSIT-IO/tdp-collection#445]
Just found out that in [roles/ranger/admin/tasks/config.yml](https://github.com/TOSIT-IO/tdp-collection/blob/b4e4c811b141b0505f8a59f8137d8beb28105a0d/roles/ranger/admin/tasks/config.yml) the rendering of _install.properties_ in done twice :
```yaml
---
- name: Template install.properties
  template:
    src: install.properties.j2
    dest: "{{ ranger_install_dir }}/install.properties"

- name: Template install.properties
  template:
    src: install.properties.j2
    dest: "{{ ranger_install_dir }}/install.properties"
...
```
