### ISSUE TITLE
Add tdp_vars to start services/components on boot

### ISSUE THREAD

**Issue by rpignolet** [TOSIT-IO/tdp-collection#447]
Inside the getting started, a playbook enable or disable systemd service on boot with variables. We should have these variables in the core collection and in extra collection. The default value should be to disable service on boot in order to start them correctly with `tdp-lib` or `tdp-server`.

The use case is for dev environnement where service can be started on boot without problem.

Core:
```yaml
hdfs_nn_start_on_boot: no
hdfs_dn_start_on_boot: no
hdfs_jn_start_on_boot: no
hdfs_zkfc_start_on_boot: no
yarn_nm_start_on_boot: no
yarn_rm_start_on_boot: no
yarn_ts_start_on_boot: no
hbase_master_start_on_boot: no
hbase_rs_start_on_boot: no
hiveserver2_start_on_boot: no
knox_start_on_boot: no
ranger_admin_start_on_boot: no
ranger_usync_start_on_boot: no
spark_hs_start_on_boot: no
spark3_hs_start_on_boot: no
zk_start_on_boot: no
```

Extra:
```yaml
livy_start_on_boot: no
livy_spark3_start_on_boot: no
kafka_start_on_boot: no
```

Some variables are missing, for example Ranger KMS. It is a list of variable currently inside the getting started.
