### ISSUE TITLE
Externalize data file configuration and set the type of database for hive and ranger

### ISSUE THREAD

**Issue by taabich** [TOSIT-IO/tdp-collection#462]
This issus is to externalize data file configuration and set the type of database for hive and ranger.
```
# Ranger Admin install.properties
install_properties:
  setup_mode: SeparateDBA
  DB_FLAVOR: MYSQL
  SQL_CONNECTOR_JAR: /usr/share/java/mysql-connector-java.jar
  db_host: localhost
  db_name: ranger
  db_user: rangeradmin
  db_password: rangeradmin
```
