### ISSUE TITLE
Make auth_to_local rules into a mergeable entity

### ISSUE THREAD

**Issue by gboutry** [TOSIT-IO/tdp-collection#463]
Since `auth_to_local` variable is a string, these rules cannot be merged.

We should turn this variable into a dict to be able to merge, such as:

## hadoop.yml tdp-collection
```yaml
auth_to_local:
    hdfs:
      - RULE:[2:$1/$2@$0]([ndj]n/.*@{{ realm }})s/.*/hdfs/
      - RULE:[1:$1@$0]({{ hdfs_headless_principal }}@{{ realm }})s/.*/hdfs/
    yarn:
      - RULE:[2:$1/$2@$0]([rn]m/.*@{{ realm }})s/.*/yarn/
      - RULE:[1:$1@$0]({{ yarn_headless_principal }}@{{ realm }})s/.*/yarn/
```
## hadoop.yml tdp-collection-extras

```yaml
auth_to_local:
    livy:
      - RULE:[2:$1/$2@$0](livy/.*@{{ realm }})s/.*/livy/
```
## hadoop.yml result of the merge
```yaml
auth_to_local:
    hdfs:
      - RULE:[2:$1/$2@$0]([ndj]n/.*@{{ realm }})s/.*/hdfs/
      - RULE:[1:$1@$0]({{ hdfs_headless_principal }}@{{ realm }})s/.*/hdfs/
    yarn:
      - RULE:[2:$1/$2@$0]([rn]m/.*@{{ realm }})s/.*/yarn/
      - RULE:[1:$1@$0]({{ yarn_headless_principal }}@{{ realm }})s/.*/yarn/
    livy:
      - RULE:[2:$1/$2@$0](livy/.*@{{ realm }})s/.*/livy/
```
## Template could look like this
```yaml
version_templated: |-
  RULE:[2:$1/$2@$0]([ndj]n/.*@{{ realm }})s/.*/hdfs/
  RULE:[1:$1@$0]({{ hdfs_headless_principal }}@{{ realm }})s/.*/hdfs/
  RULE:[2:$1/$2@$0]([rn]m/.*@{{ realm }})s/.*/yarn/
  RULE:[1:$1@$0]({{ yarn_headless_principal }}@{{ realm }})s/.*/yarn/
  RULE:[2:$1/$2@$0](livy/.*@{{ realm }})s/.*/livy/
  DEFAULT
```
