### ISSUE TITLE
Add key name templating support in the resolve plugin

### ISSUE THREAD

**Issue by leopaul36** [TOSIT-IO/tdp-collection#469]
If we want to variabilize some keys (e.g.: cluster name like in https://github.com/TOSIT-IO/tdp-collection/pull/459), we need to implement templating the keys of the variables in the `resolve` plugin.

**Comment by rpignolet** [comment]
From the merged PR.

Edge case that we choose not to support:

```yaml
number: 2
test_site:
  test_{{ test_site['test_' + (number | string)] }}: key_should_be_test_value_2
  test_{{ number }}: "value_{{ number }}"
```

This the case we want to template a key depending on another templated key.
