### ISSUE TITLE
Document passwords supported characters

### ISSUE THREAD

**Issue by Nuttymoon** [TOSIT-IO/tdp-collection#585]
After a modification of the `Create hive credentials store` task, some passwords that were supported before (e.g. one password with a `'`) trigger parsing errors.

Before:
```yaml
- name: Create hive credentials store
  shell: |
    {{ hadoop_home }}/bin/hadoop credential create javax.jdo.option.ConnectionPassword -value {{ hive_ms_db_password }} -provider {{ hive_client_credentials_store_uri }}
```
After:
```yaml
- name: Create hive credentials store
  command: >-
    {{ hadoop_home }}/bin/hadoop credential
      create javax.jdo.option.ConnectionPassword
      -value {{ hive_ms_db_password }}
      -provider {{ hive_client_credentials_store_uri }}
```

This is not necessarily a problem not to support `'` characters in passwords, but we should at least document what characters are allowed.
